config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flights
  resources :airports
  resources :bookings
  resources :passengers
  # Defines the root path route ("/")
  root "flights#index"
     
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: :departing_airport_id
  has_many :arriving_flights, class_name: "Flight", foreign_key: :arriving_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  
  accepts_nested_attributes_for :passengers, reject_if: proc { |attributes| attributes['name'].blank? }
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arriving_airport, class_name: "Airport", foreign_key: :arriving_airport_id
  belongs_to :departing_airport, class_name: "Airport", foreign_key: :departing_airport_id

  has_many :passengers, through: :bookings
  has_many :bookings

  def start_date_formatted
    self.start.to_date
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :flights, through: :bookings
  belongs_to :booking

  validates :name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @flight = find_flight
    @booking = Booking.new
    @number_of_passengers = quantity_params[:quantity].to_i
    @number_of_passengers.times do
      @booking.passengers.build
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render :index, status: :unprocessable_entity
    end
  end

  private 

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end

  def quantity_params
    params.permit(:flight_id, :commit, :quantity)
  end

  def find_flight
    Flight.find(params[:flight_id])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all

    if flight_params.empty?
      @flight_results = []
    else      
      @flight_results = find_flights
    end

  end

  private 

  def find_flights
    departure_date = departure_time_params[:start].to_date
    Flight.all.where(flight_params).where(start: departure_date.midnight..(departure_date.midnight + 1.day))
  end

  def flight_params
    params.permit(:departing_airport_id, :arriving_airport_id)
  end

  def passenger_params
    params.permit(:number_of_passengers, :start, :commit)
  end

  def departure_time_params
    params.permit(:start)
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/index.html.erb
<h1 class="header">Bookings</h1>

<% @bookings = [] if @bookings.nil? %>
<% @bookings.each do |booking| %>
  <div class="vertical-form">
    <% flight = Flight.find(booking.flight_id) %>
    <div class="form-row">
      <p>Departing from:</p> <%= Airport.all.find(flight.departing_airport_id).name %>
    </div>

    <div class="form-row">
      <p>Arriving at:</p> <%= Airport.all.find(flight.arriving_airport_id).name %> 
    </div>

    <div class="form-row">
      <p>Departure date and time</p>: <%= flight.start %>
    </div>

    <% passenger_number = 1 %>

    <% booking.passengers.each do |passenger| %>

        <p class="header">Passenger <%= passenger_number %></p>

      <div class="form-row">
        <p>Name:</p> <%= passenger.name %>
      </div>
      <div class="form-row">
        <p>Email:</p> <%= passenger.email%>
      </div>
      <% passenger_number += 1%>
    <% end %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<h1 class="header">Create New Booking</h1>

<%= form_with model: @booking, class: "vertical-form" do |form| %>
  <div class="form-row">
    <p>Departing from:</p> <%= Airport.all.find(@flight.departing_airport_id).name %>
  </div>

  <div class="form-row">
    <p>Arriving at:</p> <%= Airport.all.find(@flight.arriving_airport_id).name %> 
  </div>

  <div class="form-row">
    <p>Departure date and time</p>: <%= @flight.start %>
  </div>

  <% passenger_number = 1 %>
  <%= form.fields_for :passengers do |passenger_form| %>
    <div class="form-row">
      <p> Passenger <%= passenger_number%> </p>
    </div>

    <div class="form-row">
      <%= form.label :name, "Name:" %>
      <%= passenger_form.text_field :name %>
    </div>

    <div class="form-row">
      <%= form.label :email, "Email:" %>
      <%= passenger_form.email_field :email %>
    </div>

    <% passenger_number += 1 %>
  <% end %>

  <%= form.hidden_field :flight_id, value: @flight.id %>

  <%= form.submit "Book Flight" %>
<% end %>

app/views/bookings/show.html.erb
<h1 class="header">Booking Details</h1>

<div class="vertical-form">
  <% flight = Flight.find(@booking.flight_id) %>
  <div class="form-row">
    <p>Departing from:</p> <%= Airport.all.find(flight.departing_airport_id).name %>
  </div>

  <div class="form-row">
    <p>Arriving at:</p> <%= Airport.all.find(flight.arriving_airport_id).name %> 
  </div>

  <div class="form-row">
    <p>Departure date and time</p>: <%= flight.start %>
  </div>

  <% passenger_number = 1 %>

  <% @booking.passengers.each do |passenger| %>
    <div class="form-row">
      <p>Passenger <%= passenger_number %></p>
    </div>
    <div class="form-row">
      <p>Name:</p> <%= passenger.name %>
    </div>
    <div class="form-row">
      <p>Email:</p> <%= passenger.email%>
    </div>
    <% passenger_number += 1%>
  <% end %>
</div>

app/views/flights/index.html.erb
<h1 class="header">Search Available Flights</h1>

<%= form_with model: @flight, class: "form", method: :get do |form| %>
  <% airport_options = Airport.all.map{ |airport| [ airport.name, airport.id ] } %>
  
  <%= form.label "Departing From:" %>
  <%= select_tag(:departing_airport_id, options_for_select(airport_options, :departing_airport_id)) %>

  <%= form.label "Arriving At:" %>
  <%= select_tag(:arriving_airport_id, options_for_select(airport_options, :arriving_airport_id)) %>

  <%= form.label "Number of Passengers:" %>
  <%= select_tag(:number_of_passengers, options_for_select([1, 2, 3, 4], :number_of_passengers)) %>

  <%= form.label "Day of Departure:" %>
  <%= select_tag(:start, options_for_select(@flights.collect{|flight| flight.start_date_formatted}.uniq)) %>

  <%= form.submit "Search" %>
<% end %>

<h1 class="header">Select Flight for Booking</h1>
<%= form_with url: "/bookings/new", class: "vertical-form", method: :get do |form| %>

<% @flight_results.each do |flight| %>
  <div class="form-row">
    <label for='flight_id'><%= Airport.all.find(flight.arriving_airport_id).name %> to <%= Airport.all.find(flight.departing_airport_id).name %> departing at <%= flight.start %></label>
    <%= form.radio_button :flight_id, flight.id %>
    <%= form.hidden_field :quantity, value: params[:number_of_passengers] %>
  </div>
<% end %>

    <%= form.submit "Select Flight" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <div class="vertical-form">
      <%= link_to "All Bookings", bookings_path %>
      <%= link_to "Search Flights", flights_path %>
      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
    </div>
  </body>
</html>